-- SQL: create required tables for the DARK Shop starter
-- Run this in Supabase SQL editor (or via psql with a service-role key)

-- 1) license_keys: stores admin keys and expiry
CREATE TABLE IF NOT EXISTS public.license_keys (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE,
  username TEXT,
  product TEXT,
  expires_at TIMESTAMPTZ,
  is_used BOOLEAN DEFAULT FALSE,
  used BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 2) downloads (tools): used by admin and public site
CREATE TABLE IF NOT EXISTS public.downloads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  link TEXT,
  version TEXT,
  notes TEXT,
  visible BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 3) site_content: editable pages e.g., 'home'
CREATE TABLE IF NOT EXISTS public.site_content (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page TEXT UNIQUE NOT NULL,
  data JSONB,
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- Optional: simple index to help expiry cleanup
CREATE INDEX IF NOT EXISTS idx_license_expires_at ON public.license_keys (expires_at);

-- Note: configure Row Level Security (RLS) and policies as needed. For development
-- you can disable RLS or use your service role key for writes.



-- Add optional image fields for tools grid
ALTER TABLE IF NOT EXISTS public.downloads ADD COLUMN IF NOT EXISTS bg_image TEXT;
ALTER TABLE IF NOT EXISTS public.downloads ADD COLUMN IF NOT EXISTS thumb_image TEXT;
